### ISSUE TITLE
(Project) Fix build error on GNU/Linux: missing include for cstddef in adversarialJob.h

### ISSUE THREAD

**Issue by ceefrench** [gegelati/gegelati#93] opened 2021-12-07 21:14 UTC
When building the project an error occurs in adversarialJob.h:
`gegelati/gegelatilib/include/learn/adversarialJob.h:111:9: error: ‘size_t’ does not name a type`
The compiler suggests that `#include <cstddef>` be added at line 43, which fixes the error. 

I wasn't sure if this would be more suited to an issue or a pull request; it's a very simple fix.
I'm also relatively new to adding issues to projects, so if I got anything wrong or should provide more detail, please let me know. Cheers!

**Comment by kdesnos** [comment] 2021-12-08 08:02
Hi @ceefrench,

Thanks for your feedback and potential fix.

Can you please give a bit more details on your development environment: OS and compiler versions notably? Since `size_t` is used almost everywhere in the lib code, it is a bit weird that the problem occurs only in `adversarialJob.h` (unless this is the first occurrence of the error and the compilation stops afterwards). Also, the issue does appear on our Linux, Windows and OSX CI.

Cheers,

Karol

**Comment by kdesnos** [comment] 2022-04-20 12:00
Due to lack of details and reproducibility, I'm closing the issue.

**Closed by kdesnos** 2022-04-20 12:00 UTC
